In [1]:
import numpy as np

In [4]:
arr1=np.arange(4,24).reshape(5,4)
arr2=np.arange(6,18).reshape(6,2)
arr1
arr2

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [5]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (5,4) (6,2) 

In [8]:
arr3=np.arange(3).reshape(1,3)
arr4=np.arange(3).reshape(3,1)
arr3
arr4

array([[0],
       [1],
       [2]])

In [9]:
arr3+arr4

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
arr5=np.arange(1)
arr6=np.arange(3).reshape(1,3)
arr5

array([0])

In [14]:
arr6

array([[0, 1, 2]])

In [15]:
arr5+arr6

array([[0, 1, 2]])