In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4,5)

In [3]:
arr

array([[37, 88, 69, 99,  5],
       [13, 43, 13, 56, 63],
       [63, 16, 54, 46, 46],
       [40, 68, 33, 40, 93]], dtype=int32)

In [4]:
arr>50

array([[False,  True,  True,  True, False],
       [False, False, False,  True,  True],
       [ True, False,  True, False, False],
       [False,  True, False, False,  True]])

In [5]:
arr[arr>50]

array([88, 69, 99, 56, 63, 63, 54, 68, 93], dtype=int32)

In [7]:
arr[(arr>50) & (arr%2 == 0)]

array([88, 56, 54, 68], dtype=int32)

In [9]:
arr[(arr>50) & (arr%2 == 0)] =0

In [10]:
arr

array([[37,  0, 69, 99,  5],
       [13, 43, 13,  0, 63],
       [63, 16,  0, 46, 46],
       [40,  0, 33, 40, 93]], dtype=int32)