In [1]:
import numpy as np

In [20]:
arr1 = np.array([[1,2,3,4,5]], dtype=np.int32)
arr1

array([[1, 2, 3, 4, 5]], dtype=int32)

In [3]:
arr1.shape

(5,)

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2.shape

(2, 3)

In [15]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype=np.int32)
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

In [7]:
arr3.ndim

3

In [8]:
arr3.shape

(2, 2, 2)

In [9]:
arr3.size

8

In [16]:
arr3.itemsize

4

In [11]:
arr3.dtype

dtype('int64')

In [12]:
arr3.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [13]:
arr2.itemsize

8

In [21]:
arr1.itemsize

4