In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
arr6 = np.linspace(1,10,5)
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
arr7 = arr6.copy()
arr7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
arr8 = np.arange(6)
arr8

array([0, 1, 2, 3, 4, 5])

In [15]:
arr9 = np.arange(4,9)
arr9

array([4, 5, 6, 7, 8])

In [17]:
for i in range(2, 11, 2):
    print(i)

2
4
6
8
10
