In [4]:
import numpy as np
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(3,2)
arr3 = np.arange(12,18).reshape(2,3)

In [7]:
arr2.ndim

2

In [6]:
arr2.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [8]:
arr2.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [9]:
arr2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [11]:
np.hstack((arr1,arr3))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [12]:
np.vstack((arr1,arr3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [13]:
np.hsplit(arr3,3)

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]

In [14]:
np.vsplit(arr3,2)

[array([[12, 13, 14]]), array([[15, 16, 17]])]