In [2]:
import numpy as np
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr12[2]

array([ 8,  9, 10, 11])

In [7]:
arr12[1:4, 1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [8]:
arr12[3: , 1:]

array([[13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [9]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [10]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
