In [1]:
import numpy as np

In [2]:
np.random.random()

0.7465169905986734

In [3]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [4]:
np.random.uniform(1,100)

72.31212485077366

In [5]:
np.random.uniform(1,100,10)

array([ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093,
       35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054])

In [7]:
np.random.uniform(1,100,10).reshape(5,2)

array([[32.02899364, 69.53993895],
       [87.76252608, 89.56605969],
       [ 9.41937693,  4.86642354],
       [17.81321154, 87.93610784],
       [10.73633655, 42.68965488]])

In [8]:
np.random.randint(10)

5

In [9]:
np.random.randint(1,100,10)

array([50, 58,  4, 69, 25, 44, 77, 27, 53, 81], dtype=int32)

In [10]:
np.random.randint(1,100,10).reshape(5,2)

array([[42, 83],
       [16, 65],
       [69, 26],
       [99, 88],
       [ 8, 27]], dtype=int32)

In [11]:
a=np.random.randint(1,50,6)
a

array([26, 41, 23, 10,  4, 40], dtype=int32)

In [12]:
np.max(a)

np.int32(41)

In [13]:
np.min(a)

np.int32(4)

In [14]:
a[np.argmax(a)]

np.int32(41)

In [15]:
np.argmin(a)

np.int64(4)

In [16]:
a[a%2==1]=-1

In [17]:
a

array([26, -1, -1, 10,  4, 40], dtype=int32)

In [18]:
np.where(a%2==0,-1,a)

array([-1, -1, -1, -1, -1, -1], dtype=int32)

In [19]:
np.where(a%2==1,-1,a)

array([26, -1, -1, 10,  4, 40], dtype=int32)

In [20]:
a

array([26, -1, -1, 10,  4, 40], dtype=int32)

In [21]:
c=np.random.randint(1,50,10)

In [22]:
c

array([24, 37, 28, 38, 20, 39,  9, 33, 35, 11], dtype=int32)

In [23]:
c=np.sort(c)

In [24]:
c

array([ 9, 11, 20, 24, 28, 33, 35, 37, 38, 39], dtype=int32)

In [25]:
np.percentile(c,50)

np.float64(30.5)

In [26]:
np.percentile(c,25)

np.float64(21.0)

In [27]:
np.percentile(c,99.8)

np.float64(38.982)